#+ summary: Lists Metadata
#+ endpoint_in_url: False
#+ endpoint: http://85.214.42.229:8890/sparql/
#+ tags:
#+   - Metadata
SELECT DISTINCT ?dataset ?titleLit ?date ?license 
WHERE {
   ?dataset a void:Dataset ;
   dcterms:title ?titleLit ;
   dcterms:license ?license ;
   pav:createdOn ?date .
 }
