#+ summary: Lists Metadata
#+ endpoint_in_url: False
#+ tags:
#+   - Metadata

PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX pav: <http://purl.org/pav/>
SELECT DISTINCT ?dataset ?titleLit ?date ?license 
WHERE {
   ?dataset a void:Dataset ;
   dcterms:title ?titleLit ;
   dcterms:license ?license ;
   pav:createdOn ?date .
 }
